FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://localhost:8080
ENV NODE_ENV=development
ENV WDS_SOCKET_PORT=0
EXPOSE 3001
CMD ["npm", "start"] 