FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
# Increase memory limit and install dependencies
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm install --legacy-peer-deps
COPY . .
ENV REACT_APP_API_URL=http://localhost:8080
ENV NODE_ENV=development
ENV WDS_SOCKET_PORT=0
EXPOSE 3001
CMD ["npm", "start"] 